/* What each builtin takes and does, in one line, shown beside its name when a
   half-typed one is completed. Keyed by name; the first part is the signature,
   with the argument names jq's manual uses, and the second is what it
   produces. The words of an if, and, or and the three literals are here too,
   since they are typed in the same place a name is.

   Every name in the builtin table has an entry, and every entry names a
   builtin or one of those words; suggest.test.ts holds both, and holds each
   line short enough to read on a row of the list. */

export const DOCS: Record<string, [string, string]> = {
  '@base64': ['@base64', 'the string base64 encoded'],
  '@base64d': ['@base64d', 'the string base64 decoded'],
  '@csv': ['@csv', 'an array as one CSV row'],
  '@html': ['@html', 'the string with <, >, &, \' and " escaped'],
  '@json': ['@json', 'the value as JSON'],
  '@sh': ['@sh', 'the value quoted for a POSIX shell'],
  '@text': ['@text', 'the value as text, as tostring does'],
  '@tsv': ['@tsv', 'an array as one TSV row'],
  '@uri': ['@uri', 'the string percent-encoded for a URL'],
  add: ['add', 'the elements summed, joined or merged together'],
  all: ['all, all(f), all(g; f)', 'true when f holds for every element'],
  and: ['a and b', 'true when both are'],
  any: ['any, any(f), any(g; f)', 'true when f holds for some element'],
  arrays: ['arrays', 'the input if it is an array, else nothing'],
  ascii_downcase: ['ascii_downcase', 'the string in lower case, ASCII letters only'],
  ascii_upcase: ['ascii_upcase', 'the string in upper case, ASCII letters only'],
  booleans: ['booleans', 'the input if it is a boolean, else nothing'],
  capture: ['capture(re; flags)', 'the named groups of the match, as an object'],
  ceil: ['ceil', 'the number rounded up'],
  contains: ['contains(x)', 'true when the input contains x'],
  elif: ['if c then a elif d then b else e end', 'another condition to try'],
  else: ['if c then a else b end', 'what an if produces otherwise'],
  empty: ['empty', 'no output at all'],
  end: ['if c then a else b end', 'closes an if'],
  endswith: ['endswith(s)', 'true when the string ends with s'],
  error: ['error, error(msg)', 'fails, with msg or the input as the message'],
  exp: ['exp', 'e raised to the number'],
  exp10: ['exp10', '10 raised to the number'],
  exp2: ['exp2', '2 raised to the number'],
  explode: ['explode', 'the string as an array of code points'],
  fabs: ['fabs', 'the absolute value'],
  false: ['false', 'the boolean false'],
  first: ['first, first(f)', 'the first element, or the first output of f'],
  flatten: ['flatten, flatten(depth)', 'nested arrays unnested, depth levels down'],
  floor: ['floor', 'the number rounded down'],
  from_entries: ['from_entries', 'an object from an array of {key, value} pairs'],
  fromdate: ['fromdate', 'seconds since 1970 from an ISO 8601 date'],
  fromdateiso8601: ['fromdateiso8601', 'seconds since 1970 from an ISO 8601 date'],
  fromjson: ['fromjson', 'the value a JSON string holds'],
  getpath: ['getpath(p)', 'the value at path p, an array of keys and indexes'],
  gmtime: ['gmtime', 'seconds since 1970 broken down into date parts'],
  group_by: ['group_by(f)', 'the elements grouped into arrays by f'],
  gsub: ['gsub(re; s; flags)', 'every match of re replaced by s'],
  has: ['has(k)', 'true when the input has key or index k'],
  if: ['if c then a else b end', 'a when c is true, else b'],
  implode: ['implode', 'a string from an array of code points'],
  in: ['in(c)', 'true when c has the input as a key or index'],
  index: ['index(s)', 'where s first occurs, or null'],
  indices: ['indices(s)', 'every position where s occurs'],
  inside: ['inside(x)', 'true when x contains the input'],
  isempty: ['isempty(f)', 'true when f produces nothing'],
  iterables: ['iterables', 'the input if it is an array or object, else nothing'],
  join: ['join(sep)', 'the strings of an array, with sep between each'],
  keys: ['keys', 'the keys sorted, or the indexes of an array'],
  keys_unsorted: ['keys_unsorted', 'the keys in document order'],
  last: ['last, last(f)', 'the last element, or the last output of f'],
  length: ['length', 'the number of elements, keys or characters'],
  limit: ['limit(n; f)', 'the first n outputs of f'],
  log: ['log', 'the natural logarithm'],
  log10: ['log10', 'the base 10 logarithm'],
  log2: ['log2', 'the base 2 logarithm'],
  ltrimstr: ['ltrimstr(s)', 'the string with a leading s removed'],
  map: ['map(f)', 'f applied to each element, as an array'],
  map_values: ['map_values(f)', 'f applied to each value, keeping the keys'],
  match: ['match(re; flags)', 'each match of re, with its offset and captures'],
  max: ['max', 'the largest element'],
  max_by: ['max_by(f)', 'the element with the largest f'],
  min: ['min', 'the smallest element'],
  min_by: ['min_by(f)', 'the element with the smallest f'],
  mktime: ['mktime', 'seconds since 1970 from broken-down date parts'],
  not: ['not', 'the opposite truth value'],
  now: ['now', 'the time now, in seconds since 1970'],
  null: ['null', 'the value null'],
  nulls: ['nulls', 'the input if it is null, else nothing'],
  numbers: ['numbers', 'the input if it is a number, else nothing'],
  objects: ['objects', 'the input if it is an object, else nothing'],
  or: ['a or b', 'true when either is'],
  paths: ['paths, paths(f)', 'the path to every value, or to those passing f'],
  pow: ['pow(x; y)', 'x raised to the power y'],
  range: ['range(n), range(from; to; by)', 'the numbers from 0 or from, up to n or to'],
  recurse: ['recurse, recurse(f; cond)', 'the input and everything under it, or f repeated'],
  reverse: ['reverse', 'the elements or characters in reverse order'],
  rindex: ['rindex(s)', 'where s last occurs, or null'],
  round: ['round', 'the number rounded to the nearest whole'],
  rtrimstr: ['rtrimstr(s)', 'the string with a trailing s removed'],
  scalars: ['scalars', 'the input unless it is an array or object'],
  scan: ['scan(re; flags)', 'each match of re as a string, or its groups'],
  select: ['select(f)', 'the input when f is true, else nothing'],
  sort: ['sort', 'the elements in order'],
  sort_by: ['sort_by(f)', 'the elements ordered by f'],
  split: ['split(s), split(re; flags)', 'the string cut at each s, as an array'],
  splits: ['splits(re; flags)', 'the string cut at each match of re, as a stream'],
  sqrt: ['sqrt', 'the square root'],
  startswith: ['startswith(s)', 'true when the string starts with s'],
  strftime: ['strftime(fmt)', 'a time written out by fmt, as C strftime does'],
  strings: ['strings', 'the input if it is a string, else nothing'],
  sub: ['sub(re; s; flags)', 'the first match of re replaced by s'],
  test: ['test(re; flags)', 'true when re matches the string'],
  then: ['if c then a else b end', 'what an if produces when c is true'],
  to_entries: ['to_entries', 'an object as an array of {key, value} pairs'],
  todate: ['todate', 'seconds since 1970 as an ISO 8601 date'],
  todateiso8601: ['todateiso8601', 'seconds since 1970 as an ISO 8601 date'],
  tojson: ['tojson', 'the value as a JSON string'],
  tonumber: ['tonumber', 'the input as a number'],
  tostring: ['tostring', 'the input as a string, JSON for a container'],
  true: ['true', 'the boolean true'],
  trunc: ['trunc', 'the number with its fraction dropped'],
  type: ['type', 'the type name, such as "object" or "string"'],
  unique: ['unique', 'the distinct elements, sorted'],
  unique_by: ['unique_by(f)', 'one element per distinct f, sorted by it'],
  until: ['until(cond; next)', 'next applied until cond is true'],
  values: ['values', 'the input unless it is null'],
  walk: ['walk(f)', 'f applied to every value, innermost first'],
  while: ['while(cond; next)', 'the input and each next, while cond is true'],
  with_entries: ['with_entries(f)', 'f applied to each {key, value} pair']
};
